### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by paddy235** [Olipro/OpenVPN-LDAP-Groups#1]
[root@ecclmodel7 OpenVPN-LDAP-Groups-master]# uname -a
Linux ecclmodel7.2 3.8.13-98.7.1.el7uek.x86_64 #2 SMP Wed Nov 25 13:51:41 PST 2015 x86_64 x86_64 x86_64 GNU/Linux

OS=OracleLinux 7.2

openvpn-2.4.0

-------
[root@ecclmodel7 OpenVPN-LDAP-Groups-master]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@ecclmodel7 OpenVPN-LDAP-Groups-master]# export CFLAGS=-I/home/openvpn/include && ./configure --prefix=/home/OpenvpnLdapGroups
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc-ar... /usr/bin/gcc-ar
checking for gcc-nm... /usr/bin/gcc-nm
checking for gcc-ranlib... /usr/bin/gcc-ranlib
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking ldap.h usability... yes
checking ldap.h presence... yes
checking for ldap.h... yes
checking openvpn-plugin.h usability... yes
checking openvpn-plugin.h presence... no
configure: WARNING: openvpn-plugin.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: openvpn-plugin.h: proceeding with the compiler's result
checking for openvpn-plugin.h... yes
checking yaml-cpp/yaml.h usability... yes
checking yaml-cpp/yaml.h presence... yes
checking for yaml-cpp/yaml.h... yes
checking iostream usability... yes
checking iostream presence... yes
checking for iostream... yes
checking fstream usability... yes
checking fstream presence... yes
checking for fstream... yes
checking string usability... yes
checking string presence... yes
checking for string... yes
checking stdexcept usability... yes
checking stdexcept presence... yes
checking for stdexcept... yes
checking type_traits usability... yes
checking type_traits presence... no
configure: WARNING: type_traits: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: type_traits: proceeding with the compiler's result
checking for type_traits... yes
checking unordered_map usability... yes
checking unordered_map presence... no
configure: WARNING: unordered_map: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: unordered_map: proceeding with the compiler's result
checking for unordered_map... yes
checking list usability... yes
checking list presence... yes
checking for list... yes
checking forward_list usability... yes
checking forward_list presence... no
configure: WARNING: forward_list: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: forward_list: proceeding with the compiler's result
checking for forward_list... yes
checking functional usability... yes
checking functional presence... yes
checking for functional... yes
checking for library containing ldap_initialize... -lldap
checking for main in -lyaml-cpp... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for size_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for strdup... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating pch/Makefile
config.status: creating include/config.h
config.status: include/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

`
[root@ecclmodel7 OpenVPN-LDAP-Groups-master]# make
Making all in pch
make[1]: Entering directory `/root/setup/OpenVPN-LDAP-Groups-master/pch'
g++ -DHAVE_CONFIG_H     -Ofast -flto -Wall -std=gnu++11 -c pch.h -o pch.h.gch
pch.h:17:28: fatal error: openvpn-plugin.h: No such file or directory
 #include <openvpn-plugin.h>
                            ^
compilation terminated.
make[1]: *** [pch.h.gch] Error 1
make[1]: Leaving directory `/root/setup/OpenVPN-LDAP-Groups-master/pch'
make: *** [all-recursive] Error 1
`

**Comment by Olipro** [comment]
As the error is stating, it cannot find openvpn-plugin.h - Either you have not installed OpenVPN on the system performing the build or the header file is not located in any of your system include directories.
